// SPDX-FileCopyrightText: 2022-present Elegy Engine contributors
// SPDX-License-Identifier: MIT

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace Elegy.ECS.Generator
{
	public partial class ComponentRegistryGenerator
	{
		private void GenerateComponentKinds( SourceProductionContext production, SimpleTypeInfo registry,
			IEnumerable<SimpleTypeInfo> components )
		{
			StringBuilder sb = new();
			sb.AppendLine(
			$$"""
			// This madness was auto-generated by Elegy.ECS.Generator

			namespace {{registry.Namespace}};

			public enum ComponentKind
			{
			""" );

			foreach ( var component in components )
			{
				sb.AppendLine(
			$"""
				{component.FullName.Replace( '.', '_' )},
			"""
				);
			}

			sb.AppendLine(
			"""
			}
			""" );

			production.AddSource( $"{registry.Name}.ComponentKind.cs",
				SourceText.From( sb.ToString(), Encoding.ASCII ) );
		}

	}
}
