// SPDX-FileCopyrightText: 2022-present Elegy Engine contributors
// SPDX-License-Identifier: MIT

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Text;

/*
 * Generates something like this:
 *
 * namespace MyNamespace;
 *
 * public partial class MyEntityWorld
 * {
 *	public enum ComponentInput
 *	{
 *		Door_Open,
 *		Door_Close,
 *		...
 *		Invalid
 *	}
 *
 *	public ComponentInput StringToInputId( ReadOnlySpan<char> name )
 *	{
 *		switch ( name )
 *		{
 *		case "Door.Open":
 *			return ComponentInput.Door_Open;
 *		case "Door.Close":
 *			return ComponentInput.Door_Close;
 *		...
 *		default:
 *			return ComponentInput.Invalid;
 *		}
 *	}
 *
 *	...
 */

namespace Elegy.ECS.Generator
{
	public partial class ComponentRegistryGenerator
	{
		private void GenerateNamedEventHandling( SourceProductionContext production, SimpleTypeInfo registry,
			List<SimpleTypeInfo> components )
		{
			StringBuilder sb = new();
			sb.AppendLine(
			$$"""
			// This madness was auto-generated by Elegy.ECS.Generator

			namespace {{registry.Namespace}};

			public partial {{registry.Kind.ToString().ToLower()}} {{registry.Name}}
			{
				public enum ComponentInput
				{
			"""
			);

			foreach ( var component in components )
			{
				foreach ( var method in component.Methods )
				{
					if ( method.HasAttribute( "Input" ) )
					{
						sb.AppendLine(
			$$"""
					{{component.Name}}_{{method.Name}},
			"""
						);
					}
				}
			}

			sb.AppendLine(
			"""
					Invalid = -1
				}

				public static ComponentInput StringToInputId( ReadOnlySpan<char> name )
				{
					switch ( name )
					{
			"""
			);

			foreach ( var component in components )
			{
				foreach ( var method in component.Methods )
				{
					if ( method.HasAttribute( "Input" ) )
					{
						sb.AppendLine(
			$$"""
					case "{{component.Name}}.{{method.Name}}":
						return ComponentInput.{{component.Name}}_{{method.Name}};
			"""
						);
					}
				}
			}

			sb.AppendLine(
			"""
					default:
						return ComponentInput.Invalid;
					}
				}

				public static bool DispatchNamedEvent( fennecs.Entity entity, ComponentInput inputId )
				{
					switch ( inputId )
					{
			"""
			);

			foreach ( var component in components )
			{
				foreach ( var method in component.Methods )
				{
					if ( method.HasAttribute( "Input" ) )
					{
						sb.AppendLine(
			$$"""
					case ComponentInput.{{component.Name}}_{{method.Name}}:
						entity.Ref<global::{{component.FullName}}>().{{method.Name}}();
						break;
			"""
						);
					}
				}
			}

			sb.AppendLine(
			"""
					default:
						return false;
					}
					return true;
				}

				public static bool DispatchNamedEvent( fennecs.Entity entity, ReadOnlySpan<char> name )
				{
					ComponentInput inputId = StringToInputId( name );
					return DispatchNamedEvent( entity, inputId );
				}
			}
			"""
			);

			production.AddSource( $"{registry.Name}.NamedEventHandling.generated.cs",
				SourceText.From( sb.ToString(), Encoding.UTF8 ) );
		}
	}
}
